# Generated by Django 5.1.2 on 2024-10-25 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fluxoderotina',
            name='checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rotinadecompra',
            name='valor_total',
            field=models.FloatField(default=0.0),
        ),
    ]
